
name: Build & Push Axion UI Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    REGISTRY: ghcr.io
  # Evaluates to 'asign796/axion-ui'
    IMAGE_NAME: iamminakshi/axion-ui

jobs:
  build-and-push:
    name: Build & Push Axion UI Image
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2.Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Generate Docker image metadata
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      # 5. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
